//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinePusher
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int Id { get; set; }
        public int RoundId { get; set; }
        public int MemberId { get; set; }
        public Nullable<int> Bottles { get; set; }
        public string Delivered { get; set; }
        public string Paid { get; set; }
        public string Status { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual members members { get; set; }
        public virtual rounds rounds { get; set; }
    }
}
