//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinePusher
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class winepusherEntities : DbContext
    {
        public winepusherEntities()
            : base("name=winepusherEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<members> members { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<rounds> rounds { get; set; }
        public virtual DbSet<wines> wines { get; set; }
    }
}
